accounting/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from accounting import views



app_name = "accounting"

urlpatterns = [
    
    #Treasury :
    path('cash-transactions/',login_required(views.cash_transactions),name='cash-transactions'),
    path('add-income/',login_required(views.add_income),name='add-income'),
    path('add-expense/',login_required(views.add_expense),name='add-expense'),


    
]

dashboard/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from dashboard import views



app_name = "dashboard"

urlpatterns = [
    
    # Website :
    path('',views.website,name='website'),
    
    #Dashboard :
    path('dashboard/',login_required(views.dashboard),name='dashboard'),
    

    
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required

# from settings.views import home



urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('dashboard.urls')),

    path('userauths/', include('userauths.urls')),
    path('settings/', include('settings.urls')),
    path('accounting/', include('accounting.urls')),
    
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

settings/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from settings import views



app_name = "settings"

urlpatterns = [
    
    # Cash Categories :
    path('cash-categories-list/',login_required(views.cash_categories_view),name='cash-categories-list'),
    path('add-cash-category/',login_required(views.add_cash_category),name='add-cash-category'),
    path('edit-cash-category/',login_required(views.edit_cash_category),name='edit-cash-category'),
    path('delete-cash-category/',login_required(views.delete_cash_category),name='delete-cash-category'),

    
]

userauths/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from userauths import views


app_name = "userauths"

urlpatterns = [
    
    # Login :
    path('login/',views.LoginView.as_view(),name='login'),
    path('logout/', views.LogoutView.as_view(), name="logout"),


    # Users :
    path('users/',login_required(views.show_users),name='users'),
 
    # path('add-employer/',login_required(views.add_employer),name='add-employer'),
    # path('save-employer/',login_required(views.save_employer),name='save-employer'),
    # path('edit-employer/<int:pk>',login_required(views.edit_employer),name='edit-employer'),
    # path('update-employer/<int:pk>',login_required(views.update_employer),name='update-employer'),
    # path('employer-details/<int:pk>/',login_required(views.employer_details),name='employer-details'),
    # path('active-employer/',login_required(views.active_employer),name='active-employer'),
    # path('deactive-employer/',login_required(views.deactive_employer),name='deactive-employer'),
    
    
]

templates/partials/footer.html
<!--begin::Footer-->
<div class="footer py-4 d-flex flex-lg-column" id="kt_footer">
    <!--begin::Container-->
    <div class="container-fluid d-flex flex-column flex-md-row align-items-center justify-content-between">
        <!--begin::Copyright-->
        <div class="text-gray-900 order-2 order-md-1">
            <span class="text-muted fw-semibold me-1">2025&copy;</span>
            <span class="text-gray-800 text-hover-primary">شركة باور سبلاي - إدارة الحسابات</span>
        </div>
        <!--end::Copyright-->
        <!--begin::Menu-->
        <ul class="menu menu-gray-600 menu-hover-primary fw-semibold order-1">
            <li class="menu-item">
                <span class="menu-link px-2">Design And Dev. By Mohamed Gouda</span>
            </li>
            
        </ul>
        <!--end::Menu-->
    </div>
    <!--end::Container-->
</div>
<!--end::Footer-->

templates/partials/main_menu.html
{% load static %}
<!--begin::Aside-->
<div id="kt_aside" class="aside aside-dark aside-hoverable" data-kt-drawer="true" data-kt-drawer-name="aside" data-kt-drawer-activate="{default: true, lg: false}" data-kt-drawer-overlay="true" data-kt-drawer-width="{default:'200px', '300px': '250px'}" data-kt-drawer-direction="start" data-kt-drawer-toggle="#kt_aside_mobile_toggle">
    
    
    <!--begin::Brand-->
    <div class="aside-logo flex-column-auto" id="kt_aside_logo">
        <!--begin::Logo-->
        <a href="{% url 'dashboard:dashboard' %}">
            <img alt="Logo" src="{% static 'assets/media/logos/Logo.png' %}" class="h-40px logo" />
        </a>
        <!--end::Logo-->
        <!--begin::Aside toggler-->
        <div id="kt_aside_toggle" class="btn btn-icon w-auto px-0 btn-active-color-primary aside-toggle me-n2" data-kt-toggle="true" data-kt-toggle-state="active" data-kt-toggle-target="body" data-kt-toggle-name="aside-minimize">
            <i class="ki-outline ki-double-left fs-1 rotate-180"></i>
        </div>
        <!--end::Aside toggler-->
    </div>
    <!--end::Brand-->


    <!--begin::Aside menu-->
    <div class="aside-menu flex-column-fluid">
        <!--begin::Aside Menu-->
        <div class="hover-scroll-overlay-y" id="kt_aside_menu_wrapper" data-kt-scroll="true" data-kt-scroll-activate="{default: false, lg: true}" data-kt-scroll-height="auto" data-kt-scroll-dependencies="#kt_aside_logo, #kt_aside_footer" data-kt-scroll-wrappers="#kt_aside_menu" data-kt-scroll-offset="0">
            <!--begin::Menu-->
            <div class="menu menu-column menu-title-gray-800 menu-state-title-primary menu-state-icon-primary menu-state-bullet-primary menu-arrow-gray-500" id="#kt_aside_menu" data-kt-menu="true">
                
                <!--begin:Menu item-->
                <div class="menu-item pt-5">
                    <!--begin:Menu content-->
                    <div class="menu-content">
                        <span class="menu-heading fw-bold text-uppercase fs-7">القائمة</span>
                    </div>
                    <!--end:Menu content-->
                </div>
                <!--end:Menu item-->
                
                
                <!--begin:Menu item-->
                <div class="menu-item">
                    <!--begin:Menu link-->
                    {% url 'dashboard:dashboard' as dashboard_url %}
                    <a class="menu-link {% if request.path == dashboard_url %}active{% endif %}" href="{{ dashboard_url }}">
                        <span class="menu-icon">
                            <i class="ki-outline ki-calendar-8 fs-2"></i>
                        </span>
                        <span class="menu-title">اللوحة الرئيسية</span>
                    </a>
                    <!--end:Menu link-->
                </div>
                <!--end:Menu item-->


                <!--begin:Menu item-->
                <div data-kt-menu-trigger="click" class="menu-item menu-accordion">
                    

                    <!--begin:Menu link-->
                    <span class="menu-link">
                        <span class="menu-icon">
                            <i class="ki-outline ki-element-plus fs-2"></i>
                        </span>
                        <span class="menu-title"> الحسابات </span>
                        <span class="menu-arrow"></span>
                    </span>
                    <!--end:Menu link-->
                    <!--begin:Menu sub-->
                    <div class="menu-sub menu-sub-accordion">
                        
                        <!--begin:Menu item-->
                        <div class="menu-item">
                            <!--begin:Menu link-->

                            {% url 'accounting:cash-transactions' as cash_transactions_url %}
                            <a class="menu-link {% if request.path == cash_transactions_url %}active{% endif %}" href="{{ cash_transactions_url }}">
                                <span class="menu-bullet">
                                    <span class="bullet bullet-dot"></span>
                                </span>
                                <span class="menu-title"> حركة الخزينة </span>
                            </a>
                            <!--end:Menu link-->
                        </div>
                        <!--end:Menu item-->
                        
                        
                        
                        
                    </div>
                    <!--end:Menu sub-->
                </div>
                <!--end:Menu item-->
                
                
                


                <!--begin:Menu item-->
                <div data-kt-menu-trigger="click" class="menu-item menu-accordion">
                    <!--begin:Menu link-->
                    <span class="menu-link">
                        <span class="menu-icon">
                            <i class="ki-outline ki-element-plus fs-2"></i>
                        </span>
                        <span class="menu-title"> الموظفين </span>
                        <span class="menu-arrow"></span>
                    </span>
                    <!--end:Menu link-->
                    <!--begin:Menu sub-->
                    <div class="menu-sub menu-sub-accordion">
                        
                        <!--begin:Menu item-->
                        <div class="menu-item">
                            <!--begin:Menu link-->
                            {% url 'userauths:users' as all_users_url %}
                            <a class="menu-link {% if request.path == all_users_url %}active{% endif %}" href="{{ all_users_url }}">
                                <span class="menu-bullet">
                                    <span class="bullet bullet-dot"></span>
                                </span>
                                <span class="menu-title"> بيانات الموظفين </span>
                            </a>
                            <!--end:Menu link-->
                        </div>
                        <!--end:Menu item-->
                        
                        <!--begin:Menu item-->
                        <div class="menu-item">
                            <!--begin:Menu link-->
                            {% url 'userauths:add-user' as add_user_url %}
                            <a class="menu-link {% if request.path == add_user_url %}active{% endif %}" href="{{ add_user_url }}">
                                <span class="menu-bullet">
                                    <span class="bullet bullet-dot"></span>
                                </span>
                                <span class="menu-title">إضافة موظف</span>
                            </a>
                            <!--end:Menu link-->
                        </div>
                        <!--end:Menu item-->
                        
                        
                    </div>
                    <!--end:Menu sub-->
                </div>
                <!--end:Menu item-->


                <!--begin:Menu item-->
                <div data-kt-menu-trigger="click" class="menu-item menu-accordion">
                    

                    <!--begin:Menu link-->
                    <span class="menu-link">
                        <span class="menu-icon">
                            <i class="ki-outline ki-element-plus fs-2"></i>
                        </span>
                        <span class="menu-title"> الاعدادات </span>
                        <span class="menu-arrow"></span>
                    </span>
                    <!--end:Menu link-->
                    <!--begin:Menu sub-->
                    <div class="menu-sub menu-sub-accordion">
                        
                        <!--begin:Menu item-->
                        <div class="menu-item">
                            <!--begin:Menu link-->
                            {% url 'settings:cash-categories-list' as all_cash_categories_url %}
                            <a class="menu-link {% if request.path == all_cash_categories_url %}active{% endif %}" href="{{ all_cash_categories_url }}">
                                <span class="menu-bullet">
                                    <span class="bullet bullet-dot"></span>
                                </span>
                                <span class="menu-title"> بنود الايرادات والمصروفات </span>
                            </a>
                            <!--end:Menu link-->
                        </div>
                        <!--end:Menu item-->
                        
                        
                        
                        
                    </div>
                    <!--end:Menu sub-->
                </div>
                <!--end:Menu item-->


                
            </div>
            <!--end::Menu-->
        </div>
    </div>
    <!--end::Aside menu-->


    <!--begin::Footer-->
    <div class="aside-footer flex-column-auto pb-7 px-5" id="kt_aside_footer">
        {% comment %} <a href="https://preview.keenthemes.com/html/metronic/docs" class="btn btn-custom btn-primary w-100" data-bs-toggle="tooltip" data-bs-trigger="hover" data-bs-dismiss-="click" title="200+ in-house components and 3rd-party plugins">
            <span class="btn-label">Docs & Components</span>
            <i class="ki-outline ki-document btn-icon fs-2"></i>
        </a> {% endcomment %}
    </div>
    <!--end::Footer-->
</div>


<!--end::Aside-->

templates/partials/messages.html
{% load static %}


<link href="{% static 'assets/plugins/global/plugins.bundle.css' %}" rel="stylesheet" type="text/css"/>
<script src="{% static 'assets/plugins/global/plugins.bundle.js' %}"></script>


{% comment %} {% if messages %}
<div class="messages">
    {% for message in messages %}

    <script>
      window.onload = (function() {
    
        Swal.fire({
            icon: "{{message.tags}}",
            title: "{{message}}",
            showConfirmButton: false,
            timer: 2500
          });
      });
    </script>

    {% endfor %}
</div>
{% endif %} {% endcomment %}


{% if messages %}
<div class="messages">
    {% for message in messages %}

    <script>
      window.onload = function() {
        Swal.fire({
          text: "{{message}}",
          icon: "{{message.tags}}",
          showConfirmButton: false,
          timer: 2500
      });
      }

  </script>

    {% endfor %}
</div>
{% endif %}

templates/partials/top_menu.html
<!--begin::Wrapper-->
<div class="d-flex align-items-stretch justify-content-between flex-lg-grow-1">
    <!--begin::Navbar-->
    <div class="d-flex align-items-stretch" id="kt_header_nav">
        <!--begin::Menu wrapper-->
        <div class="header-menu align-items-stretch" data-kt-drawer="true" data-kt-drawer-name="header-menu" data-kt-drawer-activate="{default: true, lg: false}" data-kt-drawer-overlay="true" data-kt-drawer-width="{default:'200px', '300px': '250px'}" data-kt-drawer-direction="end" data-kt-drawer-toggle="#kt_header_menu_mobile_toggle" data-kt-swapper="true" data-kt-swapper-mode="prepend" data-kt-swapper-parent="{default: '#kt_body', lg: '#kt_header_nav'}">
            <!--begin::Menu-->
            <div class="menu menu-rounded menu-column menu-lg-row menu-root-here-bg-desktop menu-active-bg menu-state-primary menu-title-gray-800 menu-arrow-gray-500 align-items-stretch my-5 my-lg-0 px-2 px-lg-0 fw-semibold fs-6" id="#kt_header_menu" data-kt-menu="true">
                
                
                <!--begin:Menu item-->
                <div class="menu-item here me-0 me-lg-2">
                    <!--begin:Menu link-->
                    <span class="menu-link py-3">
                        <a href="{% url 'dashboard:dashboard' %}">
                            <span class="menu-title">اللوحة الرئيسية</span>
                        </a>
                    </span>
                    <!--end:Menu link-->
                </div>
                <!--end:Menu item-->
                

                <!--begin:Menu item-->
                <div data-kt-menu-trigger="{default: 'click', lg: 'hover'}" data-kt-menu-placement="bottom-end" class="menu-item here show menu-lg-down-accordion menu-sub-lg-down-indention me-0 me-lg-2">
                    <!--begin:Menu link-->
                    <span class="menu-link py-3">
                        <span class="menu-title">Apps</span>
                        <span class="menu-arrow d-lg-none"></span>
                    </span>
                    <!--end:Menu link-->
                    <!--begin:Menu sub-->
                    <div class="menu-sub menu-sub-lg-down-accordion menu-sub-lg-dropdown px-lg-2 py-lg-4 w-lg-250px">
                        <!--begin:Menu item-->
                        <div data-kt-menu-trigger="{default:'click', lg: 'hover'}" data-kt-menu-placement="left-start" class="menu-item menu-lg-down-accordion">
                            <!--begin:Menu link-->
                            <span class="menu-link py-3">
                                <span class="menu-icon">
                                    <i class="ki-outline ki-rocket fs-2"></i>
                                </span>
                                <span class="menu-title">Projects</span>
                                <span class="menu-arrow"></span>
                            </span>
                            <!--end:Menu link-->
                            <!--begin:Menu sub-->
                            <div class="menu-sub menu-sub-lg-down-accordion menu-sub-lg-dropdown menu-active-bg px-lg-2 py-lg-4 w-lg-225px">
                                <!--begin:Menu item-->
                                <div class="menu-item">
                                    <!--begin:Menu link-->
                                    <a class="menu-link py-3" href="apps/projects/list.html">
                                        <span class="menu-bullet">
                                            <span class="bullet bullet-dot"></span>
                                        </span>
                                        <span class="menu-title">My Projects</span>
                                    </a>
                                    <!--end:Menu link-->
                                </div>
                                <!--end:Menu item-->
                                <!--begin:Menu item-->
                                <div class="menu-item">
                                    <!--begin:Menu link-->
                                    <a class="menu-link py-3" href="apps/projects/project.html">
                                        <span class="menu-bullet">
                                            <span class="bullet bullet-dot"></span>
                                        </span>
                                        <span class="menu-title">View Project</span>
                                    </a>
                                    <!--end:Menu link-->
                                </div>
                                <!--end:Menu item-->
                                
                                <!--begin:Menu item-->
                                <div class="menu-item">
                                    <!--begin:Menu link-->
                                    <a class="menu-link py-3" href="apps/projects/settings.html">
                                        <span class="menu-bullet">
                                            <span class="bullet bullet-dot"></span>
                                        </span>
                                        <span class="menu-title">Settings</span>
                                    </a>
                                    <!--end:Menu link-->
                                </div>
                                <!--end:Menu item-->
                            </div>
                            <!--end:Menu sub-->
                        </div>
                        <!--end:Menu item-->
                        
                        <!--begin:Menu item-->
                        <div class="menu-item">
                            <!--begin:Menu link-->
                            <a class="menu-link py-3" href="apps/calendar.html">
                                <span class="menu-icon">
                                    <i class="ki-outline ki-calendar-8 fs-2"></i>
                                </span>
                                <span class="menu-title">Calendar</span>
                            </a>
                            <!--end:Menu link-->
                        </div>
                        <!--end:Menu item-->
                    </div>
                    <!--end:Menu sub-->
                </div>
                <!--end:Menu item-->
                
            </div>
            <!--end::Menu-->
        </div>
        <!--end::Menu wrapper-->
    </div>
    <!--end::Navbar-->
    <!--begin::Toolbar wrapper-->
    <div class="topbar d-flex align-items-stretch flex-shrink-0">
        
        
        
        
        <!--begin::Theme mode-->
        <div class="d-flex align-items-center">
            <!--begin::Menu toggle-->
            <a href="#" class="topbar-item px-3 px-lg-4" data-kt-menu-trigger="{default:'click', lg: 'hover'}" data-kt-menu-attach="parent" data-kt-menu-placement="bottom-end">
                <i class="ki-outline ki-night-day theme-light-show fs-1"></i>
                <i class="ki-outline ki-moon theme-dark-show fs-1"></i>
            </a>
            <!--begin::Menu toggle-->
            <!--begin::Menu-->
            <div class="menu menu-sub menu-sub-dropdown menu-column menu-rounded menu-title-gray-700 menu-icon-gray-500 menu-active-bg menu-state-color fw-semibold py-4 fs-base w-150px" data-kt-menu="true" data-kt-element="theme-mode-menu">
                <!--begin::Menu item-->
                <div class="menu-item px-3 my-0">
                    <a href="#" class="menu-link px-3 py-2" data-kt-element="mode" data-kt-value="light">
                        <span class="menu-icon" data-kt-element="icon">
                            <i class="ki-outline ki-night-day fs-2"></i>
                        </span>
                        <span class="menu-title">Light</span>
                    </a>
                </div>
                <!--end::Menu item-->
                <!--begin::Menu item-->
                <div class="menu-item px-3 my-0">
                    <a href="#" class="menu-link px-3 py-2" data-kt-element="mode" data-kt-value="dark">
                        <span class="menu-icon" data-kt-element="icon">
                            <i class="ki-outline ki-moon fs-2"></i>
                        </span>
                        <span class="menu-title">Dark</span>
                    </a>
                </div>
                <!--end::Menu item-->
                <!--begin::Menu item-->
                <div class="menu-item px-3 my-0">
                    <a href="#" class="menu-link px-3 py-2" data-kt-element="mode" data-kt-value="system">
                        <span class="menu-icon" data-kt-element="icon">
                            <i class="ki-outline ki-screen fs-2"></i>
                        </span>
                        <span class="menu-title">System</span>
                    </a>
                </div>
                <!--end::Menu item-->
            </div>
            <!--end::Menu-->
        </div>
        <!--end::Theme mode-->
        <!--begin::User-->
        <div class="d-flex align-items-stretch" id="kt_header_user_menu_toggle">
            <!--begin::Menu wrapper-->
            <div class="topbar-item cursor-pointer symbol px-3 px-lg-5 me-n3 me-lg-n5 symbol-30px symbol-md-35px" data-kt-menu-trigger="click" data-kt-menu-attach="parent" data-kt-menu-placement="bottom-end" data-kt-menu-flip="bottom">
                <img src="{{ request.user.image.url }}" alt="metronic" />
            </div>
            <!--begin::User account menu-->
            <div class="menu menu-sub menu-sub-dropdown menu-column menu-rounded menu-gray-800 menu-state-bg menu-state-color fw-semibold py-4 fs-6 w-275px" data-kt-menu="true">
                <!--begin::Menu item-->
                <div class="menu-item px-3">
                    <div class="menu-content d-flex align-items-center px-3">
                        <!--begin::Avatar-->
                        <div class="symbol symbol-50px me-5">
                            <img alt="Logo" src="{{ request.user.image.url }}" />
                        </div>
                        <!--end::Avatar-->
                        <!--begin::Username-->
                        <div class="d-flex flex-column">
                            <div class="fw-bold d-flex align-items-center fs-5">{{ request.user.full_name }}</div>
                            <a href="#" class="fw-semibold text-muted text-hover-primary fs-7">{{ request.user.job }}</a>
                        </div>
                        <!--end::Username-->
                    </div>
                </div>
                <!--end::Menu item-->
                <!--begin::Menu separator-->
                <div class="separator my-2"></div>
                <!--end::Menu separator-->
                <!--begin::Menu item-->
                <div class="menu-item px-5">
                    <a href="account/overview.html" class="menu-link px-5">تعديل الملف الشخصي</a>
                </div>
                <!--end::Menu item-->
                <!--begin::Menu item-->
                <div class="menu-item px-5">
                    <a href="apps/projects/list.html" class="menu-link px-5">
                        <span class="menu-text">My Projects</span>
                        <span class="menu-badge">
                            <span class="badge badge-light-danger badge-circle fw-bold fs-7">3</span>
                        </span>
                    </a>
                </div>
                <!--end::Menu item-->
                
                <!--begin::Menu item-->
                <div class="menu-item px-5 my-1">
                    <a href="account/settings.html" class="menu-link px-5">Account Settings</a>
                </div>
                <!--end::Menu item-->
                <!--begin::Menu item-->
                <div class="menu-item px-5">
                    {% comment %} <a href="authentication/layouts/corporate/sign-in.html" class="menu-link px-5">Sign Out</a> {% endcomment %}
                    <form action="{% url 'userauths:logout' %}" method="post">
                        {% csrf_token %}
                        <button class="btn menu-link px-5" type="submit"><i class="mdi mdi-logout text-muted fs-16 align-middle me-1"></i><span class="align-middle" data-key="t-logout">تسجيل الخروج</span></button>
                        {% comment %} <a href="#" class="btn menu-link px-5" type="submit">Sign Out</a> {% endcomment %}
                    </form>
                </div>
                <!--end::Menu item-->
            </div>
            <!--end::User account menu-->
            <!--end::Menu wrapper-->
        </div>
        <!--end::User -->
        <!--begin::Heaeder menu toggle-->
        <div class="d-flex align-items-stretch d-lg-none px-3 me-n3" title="Show header menu">
            <div class="topbar-item" id="kt_header_menu_mobile_toggle">
                <i class="ki-outline ki-burger-menu-2 fs-1"></i>
            </div>
        </div>
        <!--end::Heaeder menu toggle-->
    </div>
    <!--end::Toolbar wrapper-->
</div>
<!--end::Wrapper-->