project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required

# from settings.views import home



urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('dashboard.urls')),

    path('userauths/', include('userauths.urls')),
    path('settings/', include('settings.urls')),
    path('accounting/', include('accounting.urls')),
    
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userauths/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from userauths import views


app_name = "userauths"

urlpatterns = [
    
    # Login :
    path('login/',views.LoginView.as_view(),name='login'),
    path('logout/', views.LogoutView.as_view(), name="logout"),


    # Users :
    path('users/',login_required(views.show_users),name='users'),
 
    # path('add-employer/',login_required(views.add_employer),name='add-employer'),
    # path('save-employer/',login_required(views.save_employer),name='save-employer'),
    # path('edit-employer/<int:pk>',login_required(views.edit_employer),name='edit-employer'),
    # path('update-employer/<int:pk>',login_required(views.update_employer),name='update-employer'),
    # path('employer-details/<int:pk>/',login_required(views.employer_details),name='employer-details'),
    # path('active-employer/',login_required(views.active_employer),name='active-employer'),
    # path('deactive-employer/',login_required(views.deactive_employer),name='deactive-employer'),
    
    
]

userauths/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class User(AbstractUser):
    full_name = models.CharField(max_length=100)
    job = models.CharField(max_length=100,null=True, blank=True)
    email = models.EmailField(unique=True)
    image = models.ImageField(upload_to='users_images', default="users_images/default.jpg")


    # Delete first_name و last_name
    first_name = None
    last_name = None
    

    def __str__(self):
        return self.username

userauths/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required, permission_required
from django.views import View
from django.contrib import auth

from userauths.models import User



# Create your views here.

class LoginView(View):
    def get(self, request):

        if request.user.is_authenticated:
            messages.warning(request, "انت مسجل دخول بالفعل")
            return redirect ("/")
        else :
            return render(request, 'login.html')
    
    def post(self, request):
        username = request.POST['username'].lower()
        password = request.POST['password']

        next_url = request.POST.get('next')
        
        if username and password :
            
            user=auth.authenticate(username=username, password=password)
            if user :
                if user.is_active:
                    auth.login(request, user)
                    messages.success(request, f'مرحبا {user.full_name} تم تسجيل الدخول بنجاح')
                    return redirect(next_url)

                messages.error(request, 'تم ايقاف الحساب .. يرجي مراجعة الادارة')
                return render(request, 'login.html')

            messages.error(request, 'بيانات الدخول غير صحيحة ... حاول مره اخري')
            return render(request, 'login.html')
        
        messages.error(request, 'من فضلك املا جميع الحقول')
        return render(request, 'login.html')
    


class LogoutView(View):
    def post (self, request):
        auth.logout(request)
        messages.success(request, 'تم تسجيل الخروج من البرنامج')
        return redirect('/')




@login_required
@permission_required('userauths.view_user', raise_exception=True)
def show_users (request):
    # users = User.objects.filter(is_superuser = False)
    users = User.objects.all()
    

    context = {
        'users' : users,
        
    }
    return render (request, 'users-list.html', context)



@login_required
@permission_required('userauths.add_user', raise_exception=True)
def add_user (request):
    
    departments = Department.objects.all()
    groups = Group.objects.all()

    context = {
        'departments' : departments,
        'groups' : groups,
    }
    return render (request, 'add-user.html', context)


@login_required
@permission_required('userauths.add_user', raise_exception=True)
def save_user (request):
    
    if request.method=='POST' :
        
        full_name = request.POST.get('full_name')
        username = request.POST.get('username').lower()
        email = request.POST.get('email')
        phone = request.POST.get('phone')
        password1 = request.POST.get('password1')
        password2 = request.POST.get('password2')
        active = request.POST.get('active')
        department_id = request.POST.get('department_id')
        job = request.POST.get('job')
        details = request.POST.get('details')
        group_id = request.POST.get('group_id')

        
        if not User.objects.filter(username=username).exists():
            
            if not User.objects.filter(email=email).exists():
                if password1 != password2 or len(password1) < 6 or len(password2) < 6 :
                    messages.error(request,'Passwords Not Same Or Less than 6 Charecters')
                    return redirect("userauths:add-user")
                
                user = User.objects.create_user(
                    username=username,
                    email=email,
                    full_name=full_name,
                    job=job,
                    phone=phone,
                    details=details,
                    is_active=active,
                    is_staff=active,
                    department_id=department_id,
                )
                user.set_password(password1)
                user.save()

                if group_id:
                    my_group = Group.objects.get(id=group_id)
                    my_group.user_set.add(user)
                    

                
                messages.success(request, 'Used Added Successfuly')
                return redirect("userauths:users")
        
            else :
                messages.error(request, 'Email Used Before ... Try again')
                return redirect("userauths:users")
        else :
            messages.error(request, 'Username Used Before ... Try again')
            return redirect("userauths:users")
    
    return redirect('userauths:users')

userauths/templates/users-list copy.html
{% extends 'base.html' %}
{% load static %}

{% block title %} اسماء الموظفين  {% endblock title %}


{% block css %}

<link href="{% static 'assets/plugins/custom/datatables/datatables.bundle.css' %}" rel="stylesheet" type="text/css"/>


{% endblock css %}
    

{% block content %}

<!--begin::Main-->
<div class="app-main flex-column flex-row-fluid" id="kt_app_main">
	<!--begin::Content wrapper-->
	<div class="d-flex flex-column flex-column-fluid">
		
		<!--begin::Content-->
		<div id="kt_app_content" class="app-content flex-column-fluid">
			<!--begin::Content container-->
			<div id="kt_app_content_container" class="app-container">
				<!--begin::Card-->
				<div class="card shadow-sm">
					<div class="card-header">
						<h3 class="card-title"> بيانات الموظفين </h3>
						<div class="card-toolbar">
							
                            {% if perms.userauths.add_user %}
                            <!--begin::Primary button-->
							<a href="#" class="btn btn-sm fw-bold btn-primary" >إضافة موظف</a>
							<!--end::Primary button-->
                            {% endif %}

						</div>
					</div>
					<div class="card-body">


                        <div class="table-responsive">
                            <table id="kt_datatable_dom_positioning" class="table table-striped table-bordered gy-5 gs-7 border rounded">
                                <thead class="bg-light-primary">
                                    <tr class="fw-bold fs-7 text-gray-800 px-7">
                                        <th data-ordering="false" style="width:5%;">#</th>
                                        <th>الاسم</th>
                                        <th> الوظيفة </th>
                                        <th >القطاع</th>
                                        <th >الصلاحيات</th>
                                        <th>الحالة</th>
                                        <th style="width:15%;">Action</th>
                                        </tr>
                                </thead>
                                <tbody>
                                    {% for user in users %}
                                    <tr>
                                            
                                        <td>{{ forloop.counter }}</td>
                                        <td>{{ user.full_name }}</td>
                                        <td>{{ user.job}}</td>
                                        <td>{{ user.department}}</td>
                                        <td>
                                            {% for group in user.groups.all %}
                                                <span class="badge bg-success"> {{ group.name }} </span> {% if not forloop.last %}, {% endif %} 
                                            {% empty %}
                                                <span class="badge bg-danger text-light"> لا يوجد صلاحيات </span>
                                            {% endfor %}
                                        </td>

                                        {% if user.is_active is True %}
                                        <td><span class="badge bg-success">Active</span></td>
                                        {% elif user.is_active is False %}
                                        <td><span class="badge bg-danger text-light">DeActive</span></td>
                                        {% endif %}
                                        <td class="text-end">
                                            <a href="#" class="btn btn-sm btn-light btn-flex btn-center btn-active-light-primary" data-kt-menu-trigger="click" data-kt-menu-placement="bottom-end">Actions 
                                            <i class="ki-duotone ki-down fs-5 ms-1"></i></a>
                                            <!--begin::Menu-->
                                            <div class="menu menu-sub menu-sub-dropdown menu-column menu-rounded menu-gray-600 menu-state-bg-light-primary fw-semibold fs-7 w-125px py-4" data-kt-menu="true" style="">
                                                {% comment %} <!--begin::Menu item-->
                                                <div class="menu-item px-3">
                                                    <a href="#" class="menu-link px-3">User Details</a>
                                                </div>
                                                <!--end::Menu item--> {% endcomment %}
                                                
                                                {% if perms.userauths.change_user %}
                                                <!--begin::Menu item-->
                                                <div class="menu-item px-3">
                                                    <a href="" class="menu-link px-3">Edit User</a>
                                                </div>
                                                <!--end::Menu item-->
                                                {% if user.is_active is False %}
                                                <!--begin::Menu item-->
                                                <div class="menu-item px-3">
                                                    <a href="#" class="menu-link px-3 text-success" 
                                                    data-bs-toggle="modal" 
                                                    data-bs-target="#kt_modal_active_user"
                                                    data-id="{{ user.id }}"
                                                    data-name="{{ user.full_name }}">Active</a>
                                                </div>
                                                <!--end::Menu item-->
                                                {% elif user.is_active is True %}
                                                <!--begin::Menu item-->
                                                <div class="menu-item px-3">
                                                    <a href="#" class="menu-link px-3 text-danger" 
                                                    data-bs-toggle="modal" 
                                                    data-bs-target="#kt_modal_deactive_user"
                                                    data-id="{{ user.id }}"
                                                    data-name="{{ user.full_name }}">Deactive</a>
                                                </div>
                                                <!--end::Menu item-->
                                                {% endif %}


                                                {% endif %}
                                            </div>
                                            <!--end::Menu-->
                                        </td>
                                    </tr>
                                    {% endfor %}
                                    
                                </tbody>
                            </table>
                        </div>
						
					</div>
					
				</div>
				<!--end::Card-->
			</div>
			<!--end::Content container-->
		</div>
		<!--end::Content-->
	</div>
	<!--end::Content wrapper-->


    <!--begin::Modals -->

    {% if perms.userauths.change_user %}
    <!--begin::Modal - Deactive User-->
    <div class="modal fade" tabindex="-1" id="kt_modal_deactive_user">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h3 class="modal-title">Deactive User Account</h3>
    
                    <!--begin::Close-->
                    <div class="btn btn-icon btn-sm btn-active-light-primary ms-2" data-bs-dismiss="modal" aria-label="Close">
                        <i class="ki-duotone ki-cross fs-1"><span class="path1"></span><span class="path2"></span></i>
                    </div>
                    <!--end::Close-->
                </div>
                
                <form action="#" method="post">
                    {% csrf_token %}
                    <div class="modal-body">
                        <p class="text-danger fs-25"> Are You Sure To Deactive User Account :  </p>
                            <!--begin::Input-->
                            <input class="form-control form-control-solid" name="name" id="name"  readonly required />
                            <input class="form-control" type="hidden"  name="id" id="id" placeholder="User Name" required />
                            <!--end::Input-->
                    </div>
        
                    <div class="modal-footer">
                        <button type="button" class="btn btn-light" data-bs-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-danger">Confirm Deactive</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!--end::Modal - Deactive User -->

    <!--begin::Modal - Active User-->
    <div class="modal fade" tabindex="-1" id="kt_modal_active_user">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h3 class="modal-title">Active User Account</h3>
    
                    <!--begin::Close-->
                    <div class="btn btn-icon btn-sm btn-active-light-primary ms-2" data-bs-dismiss="modal" aria-label="Close">
                        <i class="ki-duotone ki-cross fs-1"><span class="path1"></span><span class="path2"></span></i>
                    </div>
                    <!--end::Close-->
                </div>
                
                <form action="#" method="post">
                    {% csrf_token %}
                    <div class="modal-body">
                        <p class="text-success fs-25"> Are You Sure To Active User Account :  </p>
                            <!--begin::Input-->
                            <input class="form-control form-control-solid" name="name" id="name"  readonly required />
                            <input class="form-control" type="hidden"  name="id" id="id" placeholder="User Name" required />
                            <!--end::Input-->
                    </div>
        
                    <div class="modal-footer">
                        <button type="button" class="btn btn-light" data-bs-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-success">Confirm Active</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!--end::Modal - Deactive User -->
    {% endif %}

    <!--end::Modals -->




</div>
<!--end:::Main-->

    
{% endblock content %}



{% block js %}


<script src="{% static 'assets/plugins/custom/datatables/datatables.bundle.js' %}"></script>


<script>
    

    $("#kt_datatable_dom_positioning").DataTable({
	"language": {
		"lengthMenu": "Show _MENU_",
	},
	"dom":
		"<'row mb-2'" +
		"<'col-sm-6 d-flex align-items-center justify-conten-start dt-toolbar'l>" +
		"<'col-sm-6 d-flex align-items-center justify-content-end dt-toolbar'f>" +
		">" +

		"<'table-responsive'tr>" +

		"<'row'" +
		"<'col-sm-12 col-md-5 d-flex align-items-center justify-content-center justify-content-md-start'i>" +
		"<'col-sm-12 col-md-7 d-flex align-items-center justify-content-center justify-content-md-end'p>" +
		">"
});
    
    
</script>


<script>
    $('#kt_modal_deactive_user').on('show.bs.modal', function(event) {
        var button = $(event.relatedTarget)
        var id = button.data('id')
        var name = button.data('name')
        
        var modal = $(this)
        modal.find('.modal-body #id').val(id);
        modal.find('.modal-body #name').val(name);
    
    });

    $('#kt_modal_active_user').on('show.bs.modal', function(event) {
        var button = $(event.relatedTarget)
        var id = button.data('id')
        var name = button.data('name')
        
        var modal = $(this)
        modal.find('.modal-body #id').val(id);
        modal.find('.modal-body #name').val(name);
    
    }); 

</script>


{% endblock js %}
    


    

userauths/templates/users-list.html
{% extends 'base.html' %}
{% load static %}

{% block title %} بيانات الموظفين {% endblock title %}


{% block css %}

<link href="{% static 'assets/plugins/custom/datatables/datatables.bundle.css' %}" rel="stylesheet" type="text/css"/>

{% endblock css %}
    

{% block content %}



<!--begin::Content-->
<div class="content d-flex flex-column flex-column-fluid" id="kt_content">
    <!--begin::Toolbar-->
    <div class="toolbar" id="kt_toolbar">
        <!--begin::Container-->
        <div id="kt_toolbar_container" class="container-fluid d-flex flex-stack">
            <!--begin::Page title-->
            <div data-kt-swapper="true" data-kt-swapper-mode="prepend" data-kt-swapper-parent="{default: '#kt_content_container', 'lg': '#kt_toolbar_container'}" class="page-title d-flex align-items-center me-3 flex-wrap lh-1">
                <!--begin::Title-->
                <h1 class="d-flex align-items-center text-gray-900 fw-bold my-1 fs-3"> بيانات الموظفين </h1>
                <!--end::Title-->
                
            </div>
            <!--end::Page title-->
            <!--begin::Actions-->
            <div class="d-flex align-items-center py-1">
                
                <!--begin::Button-->
                <a href="#" class="btn btn-sm btn-primary"> اضافة موظف </a>
                <!--end::Button-->
            </div>
            <!--end::Actions-->
        </div>
        <!--end::Container-->
    </div>
    <!--end::Toolbar-->
    <!--begin::Post-->
    <div class="post d-flex flex-column-fluid" id="kt_post">
        <!--begin::Container-->
        <div id="kt_content_container" class="container-xxl">
            <!--begin::Card-->
            <div class="card">
                <!--begin::Card body-->
                <div class="card-body p-0">
                    <div class="card-px py-3 my-3">


                        <table id="kt_datatable_dom_positioning" class="table table-striped table-row-bordered gy-5 gs-7 border rounded">
                            <thead class="bg-light-primary">
                                <tr class="fw-bold fs-7 text-gray-800 px-7">
                                    <th data-ordering="false" style="width:5%;">#</th>
                                    <th>الاسم</th>
                                    <th> الوظيفة </th>
                                    <th >القطاع</th>
                                    <th >الصلاحيات</th>
                                    <th>الحالة</th>
                                    <th style="width:15%;">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for user in users %}
                                    <tr>
                                            
                                        <td>{{ forloop.counter }}</td>
                                        <td>{{ user.full_name }}</td>
                                        <td>{{ user.job}}</td>
                                        <td>{{ user.department}}</td>
                                        <td>
                                            {% for group in user.groups.all %}
                                                <span class="badge bg-success"> {{ group.name }} </span> {% if not forloop.last %}, {% endif %} 
                                            {% empty %}
                                                <span class="badge bg-danger text-light"> لا يوجد صلاحيات </span>
                                            {% endfor %}
                                        </td>

                                        {% if user.is_active is True %}
                                        <td><span class="badge bg-success">Active</span></td>
                                        {% elif user.is_active is False %}
                                        <td><span class="badge bg-danger text-light">DeActive</span></td>
                                        {% endif %}
                                        <td class="text-end">
                                            <a href="#" class="btn btn-sm btn-light btn-flex btn-center btn-active-light-primary" data-kt-menu-trigger="click" data-kt-menu-placement="bottom-end">Actions 
                                            <i class="ki-duotone ki-down fs-5 ms-1"></i></a>
                                            <!--begin::Menu-->
                                            <div class="menu menu-sub menu-sub-dropdown menu-column menu-rounded menu-gray-600 menu-state-bg-light-primary fw-semibold fs-7 w-125px py-4" data-kt-menu="true" style="">
                                                {% comment %} <!--begin::Menu item-->
                                                <div class="menu-item px-3">
                                                    <a href="#" class="menu-link px-3">User Details</a>
                                                </div>
                                                <!--end::Menu item--> {% endcomment %}
                                                
                                                {% if perms.userauths.change_user %}
                                                <!--begin::Menu item-->
                                                <div class="menu-item px-3">
                                                    <a href="" class="menu-link px-3">Edit User</a>
                                                </div>
                                                <!--end::Menu item-->
                                                {% if user.is_active is False %}
                                                <!--begin::Menu item-->
                                                <div class="menu-item px-3">
                                                    <a href="#" class="menu-link px-3 text-success" 
                                                    data-bs-toggle="modal" 
                                                    data-bs-target="#kt_modal_active_user"
                                                    data-id="{{ user.id }}"
                                                    data-name="{{ user.full_name }}">Active</a>
                                                </div>
                                                <!--end::Menu item-->
                                                {% elif user.is_active is True %}
                                                <!--begin::Menu item-->
                                                <div class="menu-item px-3">
                                                    <a href="#" class="menu-link px-3 text-danger" 
                                                    data-bs-toggle="modal" 
                                                    data-bs-target="#kt_modal_deactive_user"
                                                    data-id="{{ user.id }}"
                                                    data-name="{{ user.full_name }}">Deactive</a>
                                                </div>
                                                <!--end::Menu item-->
                                                {% endif %}


                                                {% endif %}
                                            </div>
                                            <!--end::Menu-->
                                        </td>
                                    </tr>
                                    {% endfor %}
                                
                            </tbody>
                        </table>


                    </div>
                </div>
                <!--end::Card body-->
            </div>
            <!--end::Card-->



            <!--begin::Modals-->
            
            

            <!--end::Modals-->


        </div>
        <!--end::Container-->
    </div>
    <!--end::Post-->
</div>
<!--end::Content-->

    
{% endblock content %}


{% block js %}


<script src="{% static 'assets/plugins/custom/datatables/datatables.bundle.js' %}"></script>


<script>
    

    $("#kt_datatable_dom_positioning").DataTable({
	"language": {
		"lengthMenu": "Show _MENU_",
	},
    "lengthMenu": [50, 100, 200, 300],
    "pageLength": 50,
   
	"dom":
		"<'row mb-2'" +
		"<'col-sm-6 d-flex align-items-center justify-conten-start dt-toolbar'l>" +
		"<'col-sm-6 d-flex align-items-center justify-content-end dt-toolbar'f>" +
		">" +

		"<'table-responsive'tr>" +

		"<'row'" +
		"<'col-sm-12 col-md-5 d-flex align-items-center justify-content-center justify-content-md-start'i>" +
		"<'col-sm-12 col-md-7 d-flex align-items-center justify-content-center justify-content-md-end'p>" +
		">"
});

    
</script>


<script>
    $('#kt_modal_deactive_user').on('show.bs.modal', function(event) {
        var button = $(event.relatedTarget)
        var id = button.data('id')
        var name = button.data('name')
        
        var modal = $(this)
        modal.find('.modal-body #id').val(id);
        modal.find('.modal-body #name').val(name);
    
    });

    $('#kt_modal_active_user').on('show.bs.modal', function(event) {
        var button = $(event.relatedTarget)
        var id = button.data('id')
        var name = button.data('name')
        
        var modal = $(this)
        modal.find('.modal-body #id').val(id);
        modal.find('.modal-body #name').val(name);
    
    }); 

</script>


{% endblock js %}
    